server:
  port: 8001

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      ## 启用连接池
      enabled: true
      max-connections: 50
    ## 配置 ActiveMQ 信任 User类
    packages:
      trusted: com.hans.activemq.pojo,java.lang
  jms:
    ## 是否启用发布订阅模式，默认是 false
    pub-sub-domain: true
    ## 默认目的地址
    template:
      default-destination: activemq.default.destination
